ciConfig:
  dependencies:
    installDepsCmd: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
  buildArtifacts:
    buildCmd: npm run build:local
  livePreview:
    serveSetupCmd: ":"
