import * as React from "react";
import PageLayout from "../components/PageLayout";
import Banner from "../components/Banner";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
 
 
export const config: TemplateConfig = {
  stream: {
    $id: "root",
    filter: {
      savedFilterIds: ["dm_us-directory"],
    },
    fields: [
      "id",
      "uid",
      "meta",
      "name",
      "slug",
      "dm_directoryChildren.name",
      "dm_directoryChildren.slug",
      "dm_directoryChildren.dm_directoryChildrenCount"
    ],
    localization: {
      locales: ["en"],
      primary: false,
    },
  },
};
 
 
export const getPath: GetPath<TemplateProps> = ({document}) => {
    return `index.html`;
 };
 
export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({relativePrefixToRoot, path, document}): HeadConfig => {
  return {
    title: "Home Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

  const Index: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {
  const {
    _site,
    dm_directoryChildren    
  } = document;

  var sortedChildren = dm_directoryChildren.sort(function(a:any, b:any) {
    var a = a.name;
    var b = b.name;
    return (a < b) ? -1 :(a > b) ? 1 : 0;
  });
  const childrenDivs = dm_directoryChildren.map((entity:any) => (
    <div>
      <a key="uRL" href={entity.slug} className="hover:underline">
        {entity.name} ({entity.dm_directoryChildrenCount})
      </a>
    </div>
  ));


   return (
    <>
      <PageLayout _site={_site}>
        <Banner text="Home Page"></Banner>
        <div className="centered-container">
          <div className="section space-y-10 px-10">
              <h1 className="text-center">Welcome to {_site.name}!</h1>
              <div className="grid sm:grid-cols-2 md:grid-cols-4">
                {childrenDivs}
              </div>
          </div>
        </div>
      </PageLayout>
    </>
   );
 };
 
 export default Index;
 